version: '3'

services:
  client:
    build: ./frontend
    restart: always
    ports: 
      - 3000:3000
    depends_on: 
      - server

  server:
    build: ./backend
    restart: always
    environment:
      USER: root
      HOST: database
      PASSWORD: password
      DB: students_db
      PORT: 3306
    ports: 
      - 8088:8088
    depends_on: 
      - database
  
  database:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: students_db

  adminer: 
    image: adminer
    restart: always
    ports: 
      - 8080:8080
    depends_on: 
      - database

  web_server:
    image: httpd:2.4
    ports:
      - 8000:80
    volumes:
      - ./web_server/index.html:/usr/local/apache2/htdocs/index.html:ro

